#application: enpunto-1286
#version: 1
service: manager
runtime: php55
#api_version: 1

instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms #default 30ms
  max_pending_latency: automatic  #default 30ms

handlers:

#- url: /maincron
#  script: cron.php
#  login: admin

#- url: /cron-notificaciones
#  script: cron_notificaciones.php
#  login: admin

#- url: /api.*
#  script: api.php
#  secure: always


- url: /(.+\.(ico|jpg|png|gif))$
  static_files: \1
  upload: (.+\.(ico|jpg|png|gif))$
  application_readable: true
  secure: always
  login: admin

- url: /(.+\.(htm|html|css|js))$
  static_files: \1
  upload: (.+\.(htm|html|css|js))$
  application_readable: true
  secure: always
  login: admin

- url: /(.+\.(json))$
  static_files: \1
  upload: (.+\.(json))$
  mime_type: application/json
  secure: always
  login: admin

- url: /(.+\.(otf))$
  static_files: \1
  upload: (.+\.(otf))$
  mime_type: application/x-font-otf
  secure: always
  login: admin

- url: /(.+\.(woff))$
  static_files: \1
  upload: (.+\.(woff))$
  mime_type: application/x-font-woff
  secure: always
  login: admin

- url: /(.+\.(woff2))$
  static_files: \1
  upload: (.+\.(woff2))$
  mime_type: application/font-woff2
  secure: always
  login: admin

- url: /(.+\.(mp3))$
  static_files: \1
  upload: (.+\.(mp3))$
  mime_type: audio/mpeg
  secure: always
  login: admin

- url: /(.+\.php)$
  script: \1
  secure: always
  login: admin

- url: /(.+)
  script: \1.php
  secure: always
  login: admin

- url: /
  script: index.php
  secure: always
  login: admin
  
  
  